In [1]:
import pandas as pd

In [3]:
df=pd.read_csv("/kaggle/input/car-selling-price-nominal-encoding-dataset/cars.csv")
df.head()

brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

* In above DataFrame brand,fuel,and owner are the nominal fields
* nominal fields means the values of that field is equally important no one got hire priority and no one got lower priority
* for do nominal encoding we use **One Hot Encoding** concept

# One-Hot-Encoding using pandas

In [5]:
# using get_dummies() function
#for now we only apply one hot encoding on fuel and owner columns 

pd.get_dummies(df,columns=['fuel','owner']).head()

brand  km_driven  selling_price  fuel_CNG  fuel_Diesel  fuel_LPG  \
0   Maruti     145500         450000     False         True     False   
1    Skoda     120000         370000     False         True     False   
2    Honda     140000         158000     False        False     False   
3  Hyundai     127000         225000     False         True     False   
4   Maruti     120000         130000     False        False     False   

   fuel_Petrol  owner_First Owner  owner_Fourth & Above Owner  \
0        False               True                       False   
1        False              False                       False   
2         True              False                       False   
3        False               True                       False   
4         True               True                       False   

   owner_Second Owner  owner_Test Drive Car  owner_Third Owner  
0               False                 False              False  
1                True                 False              False  
2               False                 False               True  
3               False                 False              False  
4               False                 False              False

* **Let's understand what happened with the datafram when we apply one hot encoding to a DataFram,**

 **Observations:**
> 1. from fuel column 4 more columns are generated,
>> 1. fuel_CNG
>> 2. fuel_Diesel
>> 3. fuel_LPG
>> 4. fuel_Petrol
> * This are named as columnName_value
> * reason behind creating 4 column is, we have 4 different values in that column, see in below shell

> 2. from owner column 5 more columns are generated, as it have 5 different values, see in below shell

> 3. All the values are either True or False boolean
>> * if car is Diesel car then the value could be,
>> * fuel_CNG___fuel_Diesel___fuel_LPG___fuel_Petrol
>> * False______True__________False______True
>> * if car is Petrol then,
>> * False______False_________False______False

>* if We add them together considering False as 0 and True as 1 then the sum is always 1(**It cause Multicolinearity Problem**),we will see it.
>* for the slolution of this problem stay tuned...

In [12]:
print(df["fuel"].value_counts())
print()
print(df["owner"].value_counts())

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64


# n-1 One-Hot-Encoding

* here n is the no of distinct value in a column.
* as of now remember to remove **Multicolinearity problem** we use this methode
* in this methode we only create n-1 columns using get_dummies() function for n different values
* so that, the sum is always 1(as we discussed above) can be solve,

**How it can work**

* fuel_CNG___fuel_Diesel___fuel_LPG___fuel_Petrol
* False______True__________False______True

* if car is Petrol then,
* False______False_________False______False

* above example it make the column only for 3 distict values suppose it will be fuel_CNG, fuel_Diesel, fuel_LPG
* table can be,

1. if the car is Diesel then,
* fuel_CNG___fuel_Diesel___fuel_LPG
* False______True__________False

2. if car is Petrol then,
* False______False_________False

* so when value of fuel_Perol is required then,
**for case 1 it is False and for case 2 it is True**
* if True is found in the row for the fuel_xyz column then predicted value is False
* if True is **not** found in the row for the fuel_xyz column then predicted value is True

In [40]:
pd.get_dummies(df,columns=['fuel','owner'],drop_first=True).head()

brand  km_driven  selling_price  fuel_Diesel  fuel_LPG  fuel_Petrol  \
0   Maruti     145500         450000         True     False        False   
1    Skoda     120000         370000         True     False        False   
2    Honda     140000         158000        False     False         True   
3  Hyundai     127000         225000         True     False        False   
4   Maruti     120000         130000        False     False         True   

   owner_Fourth & Above Owner  owner_Second Owner  owner_Test Drive Car  \
0                       False               False                 False   
1                       False                True                 False   
2                       False               False                 False   
3                       False               False                 False   
4                       False               False                 False   

   owner_Third Owner  
0              False  
1              False  
2               True  
3              False  
4              False

* You can see i above output it drops 1st fuel_CNG column from fuel and owner_First Owner from owner
* It deletes first column of the perticular field

# One-Hot_Encoding using sci-kit Learn

* **Theory**

> * We used sci-kit learn OrdinalEncoder class for encode the data
> * With this class we only have one issue,
> * For doing encoding with this class we have to follow below steps,
>> 1. separate columns from DataFrame such a way that columns belongs to ordinal encoding is in separate group, columns belongs to nominal encoding / one hot encoding (covering soon) are in a different group.
>> 2. apply encoding algorithm.
>> 3. combine all the transformed column with untransformed column to make new DataFrame.

* **We follow above procedure for now but for avoiding this many steps we have one another concept named COLUMN TRANSFORMER (see later)**

**Step: 1 separate columns from DataFrame such a way that columns belongs to ordinal encoding is in separate group, columns belongs to nominal encoding / one hot encoding (covering soon) are in a different group.**

In [7]:
df2=df.iloc[:,2:4]
df2.head()

fuel         owner
0  Diesel   First Owner
1  Diesel  Second Owner
2  Petrol   Third Owner
3  Diesel   First Owner
4  Petrol   First Owner

**Step: 2 apply encoding algorithm.**


# Without droping

In [58]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()

In [59]:
s_array=ohe.fit_transform(df2)

#it provieds sparce matrix

In [60]:
print(s_array.toarray())
print()
print(s_array[:1,:].toarray())
print()
print(s_array[:1,:].toarray().shape)

#shape has to be 4+5=9

[[0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]]

[[0. 1. 0. 0. 1. 0. 0. 0. 0.]]

(1, 9)


# With droping

In [89]:
ohe = OneHotEncoder(drop="first")

# for include droping only need to give perameter to OneHotEncoder that is drop="first"

In [94]:
s_array=ohe.fit_transform(df2)
s_array

#it provieds sparce matrix

<8128x7 sparse matrix of type '<class 'numpy.float64'>'
	with 10910 stored elements in Compressed Sparse Row format>

In [92]:
import numpy as np

In [102]:
fuel_owner_array=s_array.toarray()
print(fuel_owner_array)
print()
print(fuel_owner_array.shape)

#shape has to be 4+5=7

[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 1. 0. 0.]
 [0. 0. 1. ... 0. 0. 1.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]

(8128, 7)


# OneHotEncoding with top categories

In [64]:
df.head()

brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [71]:
count = df['brand'].value_counts()
print(count)

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Force               6
Land                6
Isuzu               5
Kia                 4
Ambassador          4
Daewoo              3
MG                  3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64


In [74]:
# I want to put together all the brands whose count of car is <= 100

threshold=100
replace=count[count <= threshold].index
print(replace)

Index(['Nissan', 'Jaguar', 'Volvo', 'Datsun', 'Mercedes-Benz', 'Fiat', 'Audi',
       'Lexus', 'Jeep', 'Mitsubishi', 'Force', 'Land', 'Isuzu', 'Kia',
       'Ambassador', 'Daewoo', 'MG', 'Ashok', 'Opel', 'Peugeot'],
      dtype='object', name='brand')


In [81]:
temp_df = df['brand'].replace(replace,'uncommon')
temp_df.iloc[25:35,]

# don't worry replace fuction not make modefication in actual DataFrame it's create new DataFrame

25       Maruti
26       Maruti
27    Chevrolet
28       Maruti
29       Maruti
30       Maruti
31     uncommon
32       Maruti
33      Hyundai
34       Maruti
Name: brand, dtype: object

In [83]:
pd.get_dummies(temp_df).head()

BMW  Chevrolet   Ford  Honda  Hyundai  Mahindra  Maruti  Renault  Skoda  \
0  False      False  False  False    False     False    True    False  False   
1  False      False  False  False    False     False   False    False   True   
2  False      False  False   True    False     False   False    False  False   
3  False      False  False  False     True     False   False    False  False   
4  False      False  False  False    False     False    True    False  False   

    Tata  Toyota  Volkswagen  uncommon  
0  False   False       False     False  
1  False   False       False     False  
2  False   False       False     False  
3  False   False       False     False  
4  False   False       False     False

**3. combine all the transformed column with untransformed column to make new DataFrame.**

In [84]:
#We will see merging when we train our model on texual data on custome dataset
#probably it is our next task