In [2]:
import pandas as pd

In [4]:
df=pd.read_csv("/kaggle/input/customer-dataset-ordered-encoding/customer.csv")
df.head(10)

age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No
5   31  Female  Average    School       Yes
6   18    Male     Good    School        No
7   60  Female     Poor    School       Yes
8   65  Female  Average        UG        No
9   74    Male     Good        UG       Yes

In [10]:
df['review'].value_counts()

review
Poor       18
Good       18
Average    14
Name: count, dtype: int64

* Linear Regression models not work on texual data.
* so that we have to transform our column data into the numerical data

> **if your data in a perticular column is ordered then we use ordinal encoding**

* What is the meaninig of ordered data??
> * see the above DataFrame,
> * in review column there are 3 values 
>> 1. Poor
>> 2. Good
>> 3. Average
> * Good > Average > Poor
> * in short orderd means importance of the values in a same column are different.
> * also PG > UG > School

* **We are not going to apply ordered encoding for column named gender as male and female have same priority.**

* **note: Our data set does not have noise/incosistant values so we directly use it for understanding ordinal encoding**

In [15]:
from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder(categories=[["Poor","Average","Good"],["School","UG","PG"]])

#importing class of OrdinalEncoder defined by sci-kit learn

In [34]:
#below line gives us error

oe.fit(df)

ValueError: Shape mismatch: if categories is an array, it has to be of shape (n_features,).

* **Explaination**
> * We used sci-kit learn OrdinalEncoder class for encode the data
> * With this class we only have one issue,
> * For doing encoding with this class we have to follow below steps,
>> 1. separate columns from DataFrame such a way that columns belongs to ordinal encoding is in separate group, columns belongs to nominal encoding / one hot encoding (covering soon) are in a different group.
>> 2. apply encoding algorithm.
>> 3. combine all the transformed column with untransformed column to make new DataFrame.

* **We follow above procedure for now but for avoiding this many steps we have one another concept named COLUMN TRANSFORMER (see later)**

**Step: 1 separate columns from DataFrame such a way that columns belongs to ordinal encoding is in separate group, columns belongs to nominal encoding / one hot encoding (covering soon) are in a different group.**

In [27]:
df2=df.iloc[:,2:4]
df2.head()

review education
0  Average    School
1     Poor        UG
2     Good        PG
3     Good        PG
4  Average        UG

**Step: 2 apply encoding algorithm.**

In [28]:
#below line gives error as .fit() function take array not DataFrame

oe.fit(df2)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [31]:
arr_df2 = oe.transform(df2)
print(arr_df2[:10,])

[[1. 0.]
 [0. 1.]
 [2. 2.]
 [2. 2.]
 [1. 1.]
 [1. 0.]
 [2. 0.]
 [0. 0.]
 [1. 1.]
 [2. 1.]]


* **Instead of doing fit and transform seperatly you can also use fit_transorm() methode directly** 

In [33]:
arr_df2_test = oe.fit_transform(df2)
print(arr_df2_test [:10])

[[1. 0.]
 [0. 1.]
 [2. 2.]
 [2. 2.]
 [1. 1.]
 [1. 0.]
 [2. 0.]
 [0. 0.]
 [1. 1.]
 [2. 1.]]


**You can see same output is generated**

# ***small twist in the story***

* When we talk about independent variables / input columns then ordinal encoding works for ordered datapoint values
* But if the column is dependent column / dependent variable / target column then we have to use label encoding.

**Note: a point to be noted that for input columns we only use ordinal/nominal encoding and for target column we only use label encoding**

# Label encoding

In [ ]:
# same steps can also applied over here,

**Step: 1 separate columns from DataFrame such a way that columns belongs to ordinal encoding is in separate group, columns belongs to nominal encoding / one hot encoding (covering soon) are in a different group.**

In [46]:
df3 = df.iloc[:,4:5]
df3.head()

purchased
0        No
1        No
2        No
3        No
4        No

**Step: 2 apply encoding algorithm.**

In [47]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

#import LabelEncoder class of sci-kit learn

In [48]:
le.fit_transform(df3)

#transform column

/opt/conda/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 0])

In [49]:
le.classes_

#here 0 for NO and 1 for Yes

array(['No', 'Yes'], dtype=object)

**3. combine all the transformed column with untransformed column to make new DataFrame.**

In [ ]:
#We will see merging when we train our model on texual data on custome dataset